export const state = {
  pattern: null,
  playing: false,
  countingIn: false,
  step: 0,
  barIndex: 0,
  barsSinceRamp: 0,
  loop: null,
  mix: 'both',
  currentId: null,
  lastRealPatternId: null,
  riffLock: false,
  fretboardApi: null,
  suppressPersist: false,
};
